services:
  localstack:
    container_name: "localstack_fintech"
    image: localstack/localstack:3.0.0
    ports:
      - "4566:4566"
    environment:
      - SERVICES=s3,dynamodb,iam,kms,lambda
      - DEBUG=1
    volumes:
      - "./localstack_data:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4566/_localstack/health"]
      interval: 10s
      timeout: 5s
      retries: 5
